Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (61,'How many 2-cents stamps does it take to make a dozen?','6','12','10','0',3,null,null,'12','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (62,'We sound like flatfish, but have no doubt. On frozen water, we`re assests to get you about.','Hovercraft','Skates','Walking','Bicycle',3,null,null,'Skates','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (63,'I am called by many yet I have no name. I am recognised digitally only. What am I?','A blackberry','Piano key','A potato','A phone number',3,null,null,'A phone number','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (64,'If you were running a race, and you passed the person in second place, what place would you be in now?','1','4','2','3',3,null,null,'2','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (65,'Which fruits come every month?','Your father','Dates','Church','Shadow',3,null,null,'Dates','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (66,'Take away my first letter, and the rest you will find in newspapers, magazines, and jouranls. What am I ?','Particles','Radiation','Notes','Paper',3,null,null,'Particles','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (67,'The more you have it, the less you see. What is it ?','Blindness','Cupcakes','Darkness','Hatred',3,null,null,'Blindness','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (68,'What has a head, a tail, is brown and has no legs ?','A Stack Of Apple','Ant','Penny','Apple',3,null,null,'Penny','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (69,'At night the come without being fetched. By day they are lost without being stolen. What are they ?','A Knight','A Child','The Stars','A Caterpillar',3,null,null,'The Stars','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (70,'Whats black when you get it, red when you use it, and white when you are all through with it ?','A Paper','Gas Stove','Charcoal','Knife',3,null,null,'Charcoal','E');


Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (71,'If you divide 14 by its half, what do you get?','25','19','10','7',3,null,null,'7','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (72,'I bend in 3 places and can beckon or accuse. I`m known to make a very good point. What am I?','A blackberry','Piano key','Index finger','A phone number',3,null,null,'Index finger','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (73,'If there is a basket of 13 apples and you take three of them,how many apples do you have?','1','10','3','0',3,null,null,'3','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (74,'With pointed fangs, i sit in wait. With piercing force, I dole out fate. Over bloodless victims proclaiming might. Eternally joining with a single bite. What am I?','Candle','Banana','Staple ','Fingernail',3,null,null,'Staple ','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (75,'If you look at my face, there wont be thirteen in any place ?','Friday the 13th','A Clock','A Calender','A Scoreboard',3,null,null,'A Clock','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (76,'What has roots as nobody sees, is taller than trees. Up, up, up it goes, and yet it never grows ?','A Tree','A Flower','A Seed','A Mountain',3,null,null,'A Mountain','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (77,'People want to keep me. I am always very quiet. Half of me is a vegetable, the other is a card up your sleeve.','Peace','Patience','A Carrot','A Turtle',3,null,null,'Peace','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (78,'I am always hungry, I must always be fed. The finger I touch, will soon turn red.','Fire','A Stainless Nettle','A Bee','Water',3,null,null,'Fire','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (79,'The person who makes it, sells it. The person who buys it never uses it and the person who uses it doesnt know what they are.','Apples','Flowers','Water','A Coffin',3,null,null,'A Coffin','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (80,'What has a mouth but never eats ?','Mouse','Flower','Nothing','River',3,null,null,'River','M');


Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (81,'Your maternal uncles only brother in law is laying on the couch. Who is he?','Potato','Snowman','Your father','Dates',3,null,null,'Your father','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (82,'I can point the way when I am full. When empty, nothing moves me. I have two skins; one without and one within. What am i?','A snowman','Time','A liss','Glove',3,null,null,'Glove','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (83,'Spelling a problem, flip open my pages. I am the voice of authority in the modern ages. Adjective, verb, noiun, In me, the answer can be found.','Tape','Commercial','Eraser','Dictionary ',3,null,null,'Dictionary ','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (84,'Two fathers and two sons went into a bar to have a drink together. They spent fifteen pounds altogether and each man spent the same amount. How much did each man spend?','One pound','Six pounds','Two pounds','Five pounds',3,null,null,'Five pounds','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (85,'If a rooster is perched on the top of a ban with the barn roof sloping east and west,and just as the sun rises the rooster lays an egg,on which side of the barn will egg roll?','Both','East','Neither','West',3,null,null,'Neither','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (86,'I am often aglow from a fire within. If you take away my end, you will be home again. What am I?','Time','Glove ','Shadow','Hearth ',3,null,null,'Hearth ','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (87,'I am only one color,but not one size. I can be stuck at the bottom,but easily rise. I am present in sun,but rarely in rain. I can do no harm and fell no pain. What am I?','Time','Glove ','Shadow','Hearth ',3,null,null,'Shadow','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (88,'I sit astraddle, and brings back vision for some. Some use me for style, just make sure i dont have a degree! What am I ?','Spectacles','A Lens','A Magnifying Glass','A Microscope',3,null,null,'Spectacles','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (89,'I am the root of all the evil, the love at first sight. Though I am lethal, I am still worth the fight. What am I ?','Beauty','Envy','Money','Popularity',3,null,null,'Money','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (90,'I make you weak at the worst of times. I make your heart grow cold. I visit the weak, but seldom the bold.','Fear','A Bully','A Nightmare','A Ghost',3,null,null,'Fear','D');