Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (91,'Snake skulls are made up of many tiny bones to help them do what ?','Hear better','Conserve hear','Avoid detection','Swallow big meals',4,null,null,'Swallow big meals','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (92,'What species of reptile is a Gharial ?','Crocodile','Alligator','Iguana','Snake',4,null,null,'Crocodile','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (93,'Chameleon gets its name from some Latinized Greek. What does its name literally mean ?','Ground Lion','Dead Flower','Transformed Leather','Colorful Lizard',4,null,null,'Ground Lion','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (94,'Which of the following pairs is most closely related ?','Snake and Lizard','Crocodile and Tuatara','Alligator and Komodo dragon','Alligator and Turtle',4,null,null,'Snake and Lizard','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (95,'Sea snakes and turtles breathe','with gills','with lungs','through their skin','through their chorion',4,null,null,'with lungs','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (96,'Snakes are thought to have evolved from','Crocodiles','Lizards','Eels','Ventricle',4,null,null,'Lizards','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (97,'Which of the following is not a reptile','Lizards','Snakes','Tortoise','Eagle',4,null,null,'Eagle','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (98,'Which is a property of the reptiles ?','Most are Hot-Blooded','Most are Blind','Most are Cold-Blooded','Most have 2 Hearts',4,null,null,'Most are Cold-Blooded','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (99,'Which lizard uses its chromatophore cells to change color with its moods ?','Chameleon','Anole','Skink','Gecko',4,null,null,'Chameleon','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (100,'Why are most reptiles voiceless ?','They lack tounges','They lack lungs','They lack full mouths','They lack vocal chords',4,null,null,'They lack vocal chords','E');


Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (101,'Including their tail, iguanas can grow to be about how long ?','6.5 Feet','3 Feet','1 Foot','12 Feet',4,null,null,'6.5 Feet','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (102,'Which is the largest living reptile in the world ?','Saltwater Crocodile','American Alligator','Komodo Dragon','Nile Crocodile',4,null,null,'Saltwater Crocodile','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (103,'The komodo dragon is native to the islands of which country ?','Hawaii','Indonesia','New Zealand','Belgium',4,null,null,'Indonesia','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (104,'The worlds fastest snake is also the largest venoumous snake in Africa. What is it ?','Bushmaster','Black Mamba','Copperhead','Death Adder',4,null,null,'Black Mamba','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (105,'The top of turtles shell is called the','Plastron','Cloaca','Carapace','Rynchocephalia',4,null,null,'Carapace','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (106,'Which of the following reptiles have a third eye and only live in New Zealand ?','Tuatara','Komodo Dragon','Gila Monster','Anaconda',4,null,null,'Tuatara','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (107,'What best characterizes the nature of most reptile eggs ?','Hornlike, Delicate','Leathery, Tough','Slimy, Fragile','Just like bird eggs',4,null,null,'Leathery, Tough','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (108,'Giant tortoise can grow upto how many pounds ?','230 Pounds','150 Pounds','660 Pounds','1100 Pounds',4,null,null,'660 Pounds','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (109,'Most reptiles exchange gasses through what feature ?','Jacobson Organ','Gills','Stomach','Lungs',4,null,null,'Lungs','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (110,'The heat sensing organs between the eyes and nostril of a rettlesnake are what ?','VR Organs','Brain Extension','Pit Organs','Shell Sensor',4,null,null,'Pit Organs','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (111,'The biggest Komodo Dragon reached how long in length ?','2.2 Feet','7.6 Feet','1.9 Feet','10.3 Feet',4,null,null,'10.3 Feet','M');


Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (112,'Which continent boasts the most different species of discovered reptiles ?','Europe','Africa','North America','Asia',4,null,null,'Asia','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (113,'How many species of African clawed geckos are there in the world ?','2','5','4','3',4,null,null,'2','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (114,'There are how many species of rainbow boas in the world ?','10','30','40','20',4,null,null,'10','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (115,'What snake is Britains only venoumous reptile ?','Pit Viper','Adder','Cobra','Garter snake',4,null,null,'Adder','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (116,'Which is the largest of the 5 species of chuckwalla species of lizard ?','Common chackwalla','San Esteban chackwalla','Angel Island chackwalla','Peninsular chackwalla',4,null,null,'San Esteban chackwalla','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (117,'You would find there are no alligators in tha Alligator River, but you would find crocodiles. Where are you ?','Australia','South Africa','India','Florida',4,null,null,'Australia','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (118,'which of these is a native location for a boa constrictor ?','South America','Africa','Europe','Antarctica',4,null,null,'South America','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (119,'Caimans are most closely related to which animals ?','Chameleons','Turtles','Alligators','Geckos',4,null,null,'Alligators','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (120,'How many pairs of cranial nerves do reptiles have ?','12','2','6','1',4,null,null,'12','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (121,'The blue-lipped sea krait is found in which ocean ?','Indian Ocean','Southern Ocean','Atlantic Ocean','Pacific Ocean',4,null,null,'Indian Ocean','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (122,'Where is the only place you will find native flying reptiles ?','Hawaii','Mozambique','India','Borneo',4,null,null,'Borneo','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (123,'The name of what reptile means WORM OF THE PEBBLES ?','Turtle','Crocodile','Frog','Komodo Dragon',4,null,null,'Crocodile','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (124,'The horned lizard is the state reptile of which US State ?','New York','New Jersey','Vermont','Wyoming',4,null,null,'Wyoming','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (125,'For which US State is the garter snake the state reptile ?','Massachusetts','Michigan','Maryland','Louisiana',4,null,null,'Massachusetts','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (126,'What is the name of the smallest species of crocodile in the world ?','Tiny Crocodile','Dwarf Crocodile','Midget Crocodile','Pygmy Crocodile',4,null,null,'Dwarf Crocodile','D');

