Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (127,'Which nation was the first to win football World Cup ?','Mexico','England','Uruguay','Germany',5,null,null,'Uruguay','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (128,'Offa s Dyke largely follows the border between England and where ?','France','Wales','Normandy','Ireland',5,null,null,'Wales','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (129,'Who was Osama bin Ladens father ?','Muhammed','Ali','Azzam','Raul',5,null,null,'Muhammed','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (130,'Which European country is ruled by The House Of Oranges ?','Norway','Netherlands','Sweden','Belgium',5,null,null,'Netherlands','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (131,'In which century was World War I ?','21st','14th','20th','18th',5,null,null,'20th','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (132,'How many minutes did Neil Armstrong spend on the moon ?','12','152','62','1162',5,null,null,'152','E');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (133,'Nelson Mandela spent most of his time in what prison, now a tourist attraction off Cape Town ?','Ellesmere Island','Baffin Island','Robben Island','Victoria Island',5,null,null,'Robben Island','E');


Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (134,'Which English Kings remains were eventually discovered under a modern parking lot ?','Henry II','Richard III','Edward I','John',5,null,null,'Richard III','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (135,'What weapon dominated the Battle of Agincourt in the Hundred Years War ?','Broadsword','Longbow','Musket','Cannon',5,null,null,'Longbow','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (136,'Iwo Jima was hard fought over in WW2. Which country controls the island today ?','Japan','Russia','Phillippines','United States',5,null,null,'Japan','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (137,'Who was sworn in for a second term as minister of Pakistan in 1993 ?','Nawaz Sharif','Nurul Amin','Benazir Bhutto','Shaukat Aziz',5,null,null,'Benazir Bhutto','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (138,'In 1492 where did Christopher Columbus make his first landing in the new world ?','Bahamas','Jamaica','Puerto Rico','Florida',5,null,null,'Bahamas','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (139,'Which of these nations changed sides partway through World War II ?','Spain','United Kingdom','Italy','Japan',5,null,null,'Italy','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (140,'Which US President was born in 1946 and is known as BUBBA ?','George Washington','John Adams','Abraham Lincoln','William Jefferson Clinton',5,null,null,'William Jefferson Clinton','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (141,'Who married a Shanghai actress whose stage name was Lan Ping, meaning Blue Apple ?','Kim Jung-II','Mao','Ho Chi Minh','Hirohito',5,null,null,'Mao','M');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (142,'Who founded both Time and Life magazines ?','Clarles Foster Kane','Rupert Murdoch','Henry Luce','William Randolph Hearst',5,null,null,'Henry Luce','M');


Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (143,'Between 1807 and 1821 the capital of Portugal was found in which city ?','London','Goa','Madrid','Rio de Janerio',5,null,null,'Rio de Janerio','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (144,'Which British monarch lost the 13 American colonies during his reign ?','Henry V','William IV','George III','George I',5,null,null,'George III','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (145,'Which general defeated the French in Canada ?','Lambe','Wolfe','Hogge','Hawke',5,null,null,'Wolfe','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (146,'Who preceded Fidel Castro as politician leader of Cuba ?','Fulgencio Batista','Norberto Martin','Raoul Hernandez','Juan Peron',5,null,null,'Fulgencio Batista','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (147,'How old was Ronald Reagan when he died on June 5, 2004 ?','87','100','90','93',5,null,null,'93','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (148,'What was found in Rosetta in Egypt in 1799 that got Europeans all excited ?','A papyrus letter','An inscribed stone','A secret tomb','A mummified prince',5,null,null,'An inscribed stone','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (149,'In which year did Charles Lindbergh fly across the Atlantic ?','1907','1927','1917','1937',5,null,null,'1927','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (150,'Antonio de Oliveira Salazar served as leader of which nation from 1932-1968 ?','Mexico','Greece','Spain','Portugal',5,null,null,'Portugal','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (151,'In which year did Texas become a US State ?','1912','1959','1845','1861',5,null,null,'1845','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (152,'Botany Bay was the first penal colony in which Australian state ?','Tasmania','South Australia','Queensland','New South Wales',5,null,null,'South Australia','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (153,'On which island was Captain Cook killed in 1779 ?','Australia','Moluccan Islands','Hawaii','New Zealand',5,null,null,'Hawaii','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (154,'Who wrote the 95 theses against the Catholic Church ?','Jean Calvin','John Huss','Pope Leo III','Martin Luther',5,null,null,'Martin Luther','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (155,'Which painter was considered the prime artist of the French Revolution ?','Dali','Turner','Van Gogh','David',5,null,null,'David','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (156,'What industrialist became famous for his defiance of a dictator ?','Henry Ford','Howard Hughes','Louis Renault','Oskar Schindler',5,null,null,'Oskar Schindler','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (157,'In which year did the first passenger die in a rail accident ?','1870','1780','1830','1850',5,null,null,'1830','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (158,'In which year did the hula hoop craze first circle the world ?','1966','1963','1958','1952',5,null,null,'1958','D');
Insert into QUESTIONBANK (QNO,QUES,A1,A2,A3,A4,TOPICNO,WRONGLYANSD,CORRECTLYANSD,CORRECTANS,DIFFICULTY) values (159,'Jackie Robinson is best related to which of these facts ?','Editor of Washington Post','Produced an Affordable Car','Head of Multimedia Empire','Broke Baseballs Color Barrier',5,null,null,'Head of Multimedia Empire','D');

